### PR TITLE
Changes to get parliament2 working with Singularity on HPC systems

### PR DESCRIPTION
**Pull request by sameerd**
This PR is in reference to issue #41 

Here are the changes that were needed to get parliament2 built with Docker and then run with Singularity.  The Singularity container runs as the same user inside the container as the user outside the container. This user has permissions to read the `/home/dnanexus` directory but can write to only specific places in the container. The main change is to limit the places where the app writes to the following three directories

1. `/home/dnanexus/in`
2. `/home/dnanexus/out`
3. A working directory which is unspecified beforehand. 

In order to do this we need to make a few types of changes

1. Fixing paths so some are hardcoded and some are relative to the unspecified working directory.
2. Pre-installing `svtyper` and `svviz` into their own environments so that they are pre-built at compile time and not at run time. 
3. Switching environments to run the right programs
4. A fix that was required to make the command `parallel` run (not quite related to this PR)

Here are the changes to the 6 files that were changed and a brief description of the changes. 

1. `Dockerfile`
   - Copy `svtyper_env.yml` into the container. This is required to create the svtyper conda environment
   - Create two different conda environments in addition to the default
2. `hooks/pre_build`
   - Optional file needed to build on dockerhub 
3. `parliament2.sh`
    -  Changing paths. Hardcoding `/home/dnanexus` whenever required and also making some paths relative paths
    - switching conda environments
4. `resources/home/dnanexus/parallelize_svtyper.sh`
     - removing the `memfree` option from parallel in order to make it run
5. `resources/usr/bin/runManta`
    - Changing paths
6. `svtyper_env.yml`
    - File to create conda environment from git

With these changes, I was able to build the container on [Dockerhub](https://hub.docker.com/) and then pull down the docker container with singularity `singularity pull docker://sameerdcosta/parliament2` and then run with 
```shell
 LANG= singularity run \
        -B `pwd`/input:/home/dnanexus/in:rw \
        -B `pwd`/output:/home/dnanexus/out:rw \
        parliament2_latest.sif   \
            --bam input.bam \
            --bai input.bam.bai \
            -r human_g1k_v37.fasta \
            --fai human_g1k_v37.fasta.fai \
            --breakdancer --breakseq  --manta \
            --cnvnator --lumpy --genotype 
```

I'm happy to make changes to the PR should they be required. Thanks again!

### CODE REVIEW

**Comment by sameerd** [comment]
@slzarate It looks like the logs say that `docker login --username` is needed instead of `docker login -u`.  I haven't done Travis CI before so I'm not sure.

```
$ echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin && docker push dnanexus/parliament2:latest
Must provide --username with --password-stdin
The command "echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin && docker push dnanexus/parliament2:latest" exited with 1.
```

**Comment by slzarate** [comment]
Yep, I am working on it

**Comment by sameerd** [comment]
@slzarate It looks like all the checks passed except the last one which timed out!. That's encouraging 👍

**Comment by slzarate** [comment]
Great! It's very promising that the tests all work.

It looks like all of the tests take a lot more time than usual. Unfortunately, I've been in touch with the Travis CI people, and tests can't last for more than 3h. However, the last test tests all of the callers together, which isn't strictly necessary, so I can remove it. Let me run some further tests to ensure that everything still works on DNAnexus. I'll keep you posted.

**Comment by slzarate** [comment]
@sameerd It looks like everything checks out on DNAnexus. Let me get the tests working and then you can merge to master! Thanks so much for all of your help!

**Comment by slzarate** [comment]
@sameerd It doesn't look like I can push to your branch directly. Can you please change line 31 of the `.travis.yml` file to:

```
- script: docker run -v /home/dnanexus/in:/home/dnanexus/in -v /home/dnanexus/out:/home/dnanexus/out dnanexus/parliament2:$TAG --bam /home/dnanexus/in/small_input.bam --bai /home/dnanexus/in/small_input.bai --ref_genome /home/dnanexus/in/ref.fa.gz --fai /home/dnanexus/in/ref.fa.fai --prefix full --breakdancer --breakseq --genotype && ls -sh /home/dnanexus/out
```

(you can just copy-paste it.) This should allow the test to work. Thanks

**Comment by sameerd** [comment]
@slzarate I added the `.travis.yml` change you recommended. Also I added you as a collaborator on my branch so you can push to it if you need to.

**Comment by slzarate** [comment]
@sameerd Thanks, I appreciate it. I'll go ahead and merge it once it's ready. Thanks again for your help!

**Comment by sameerd** [comment]
I’m going to close and re-open this request to allow Travis-CI to run again. It appears that most of the failures this time were HTTP timeout requests. 

Ps. On a side note, I wonder if it is possible to build the container once and then use it for all the tests instead of building it separately each time.

**Comment by sameerd** [comment]
Yay! This is working now. Nice work @slzarate

**Comment by slzarate** [comment]
I have been working to try to get the container built only once... Pushing it to the Dockerhub repository and pulling it was the closest I'd gotten, but as we've seen, it doesn't work with external collaborators' pull requests. I am still thinking on the best way of doing this.

So glad this works now! I will merge it shortly. Thank you for all your help on this @sameerd!

**Comment by sameerd** [comment]
@slzarate no need to thank me. I need to thank you for saving many weeks of time for me and others! :-)

I see that this PR passed CI but failed when it was merged into master. The failures were mostly timeouts. The git repo is quite large now after commit #53 `git pull` on my local machine downloaded around 2GB of  git objects. So to get Travis CI working reliably it might be worth figuring out how to not pull the entire git tree to Travis and also how to  build the container just once. 

I don't know if this is possible but a quick google search shows that other people have run into this problem as well.

**Comment by slzarate** [comment]
@sameerd OK, I will look into how to not clone the entire repo (the culprit is the benchmarking files and outputs that we are including for reference). Thanks!

**Comment by ManavalanG** [comment]
In my case of running parliament2 with singularity in SLURM, working directory was my home directory, which is not ideal. It ends populating too many files in my home directory. I resolved this by specifying a custom directory as home (e.g. ```singularity run --home `pwd`/custom_home:$HOME)```.

Parliament2 version used: 0.1.11

**Pull request merged**
